// Code generated by "stringer -type=String"; DO NOT EDIT.

package state

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[StringStart-1]
	_ = x[StringFirstQuote-2]
	_ = x[StringCodepoint-3]
	_ = x[StringEscapeSymbol-4]
	_ = x[StringEscape-5]
	_ = x[StringHexDigitSymbol-6]
	_ = x[StringHexDigit1-7]
	_ = x[StringHexDigit2-8]
	_ = x[StringHexDigit3-9]
	_ = x[StringHexDigit4-10]
	_ = x[StringLastQuote-11]
	_ = x[StringEnd-12]
}

const _String_name = "StringStartStringFirstQuoteStringCodepointStringEscapeSymbolStringEscapeStringHexDigitSymbolStringHexDigit1StringHexDigit2StringHexDigit3StringHexDigit4StringLastQuoteStringEnd"

var _String_index = [...]uint8{0, 11, 27, 42, 60, 72, 92, 107, 122, 137, 152, 167, 176}

func (i String) String() string {
	i -= 1
	if i >= String(len(_String_index)-1) {
		return "String(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _String_name[_String_index[i]:_String_index[i+1]]
}
