// Code generated by "stringer -type=Array"; DO NOT EDIT.

package state

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ArrayFirstValue-1]
	_ = x[ArrayValue-2]
	_ = x[ArraySeparator-3]
}

const _Array_name = "ArrayFirstValueArrayValueArraySeparator"

var _Array_index = [...]uint8{0, 15, 25, 39}

func (i Array) String() string {
	i -= 1
	if i >= Array(len(_Array_index)-1) {
		return "Array(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _Array_name[_Array_index[i]:_Array_index[i+1]]
}
