// Code generated by "stringer -type=Object"; DO NOT EDIT.

package state

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ObjectKey-1]
	_ = x[ObjectColon-2]
	_ = x[ObjectValue-3]
	_ = x[ObjectSeparator-4]
}

const _Object_name = "ObjectKeyObjectColonObjectValueObjectSeparator"

var _Object_index = [...]uint8{0, 9, 20, 31, 46}

func (i Object) String() string {
	i -= 1
	if i >= Object(len(_Object_index)-1) {
		return "Object(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _Object_name[_Object_index[i]:_Object_index[i+1]]
}
